version: "3.8"

services:
  airflow:
    build:
      context: ./docker/airflow
    container_name: airflow_container
    restart: always
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    command: >
      bash -c "
      airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
      airflow scheduler &
      airflow webserver"
    depends_on:
      - dbt

  dbt:
    build:
      context: ./docker/dbt_project # Ensure the Dockerfile is in the correct directory
    container_name: dbt_container
    volumes:
      - ./docker/dbt_project:/usr/app/dbt_project
      - ./docker/dbt_project/profiles.yml:/root/.dbt/profiles.yml
      - ./data/processed:/usr/app/data/processed
    command: tail -f /dev/null
    tty: true

  dash:
    build:
      context: ./docker/dash_app
    container_name: dash_app
    volumes:
      - ./data/processed:/usr/app/data/processed
    ports:
      - "8050:8050"
    command: python app.py
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"