version: 2

models:
  - name: combined_analysis
    description: "Model to analyze traffic accidents by region and type"
    columns:
      - name: Maakond
        description: "The region where the traffic accident occurred"
      - name: Liiklusõnnetuse liik
        description: "The type of traffic accident"
      - name: total_accidents
        description: "The total number of traffic accidents"

  - name: test_table
    description: "A test table selecting 5 rows from integrated_data"
    columns:
      - name: accident_id
        description: "Unique identifier for the accident"
      - name: accident_date
        description: "Date of the accident"